angr/claripy

- claripy/frontends/full_frontend.py
The _tls attribute was set to None, which prevented loading a pickled Path object. Initialized based __init__.
> Initialized _tls attribute in _ana_setstate for FullFrontend class.

- claripy/bv.py
I am shifting with BVV of size 256, and I encountered overflows because of that python2 specificity.
> Fix a bug caused by http://bugs.python.org/issue8259

- setup.py
Without this change, you can't use a claripy downloaded using pip.
> Update setup.py with the new module.

- claripy/backends/backend_z3.py
This solves the issue I was complaining about in slack.
For the binary that I'm working on, which I can't share, and is also probably malware, this changes angr's behavior from "crash and burn with a z3 exception after about 2000 blocks" to "run out of memory after about 8000 blocks". I suspect that this binary has logic which detects if it's being emulated and tries to fuck up its emulator, like what we did in cgc.
> store string instead of integer for z3 ast hash

- claripy/ast/base.py
when the address expression was a ite, the added annotation in _normalize_address_type (abstract_memory.py) was removed by the ite_excavated property, causing a bug during CFG construction.
> ite_excaveted triggered  a bug in normalize_address_type

- claripy/operations.py
Filtering out all \_\_xor__ args leads to \_\_xor__ over an empty tuple which is undefined without an initial value, so it is followed by TypeError('reduce() of empty sequence with no initial value').
_flatten_simplifier is now provided with corresponding initial value.
> Fix bitwise xor simplifier

- claripy/backends/backend_z3.py
For some reason, when using PyPy, tactics are never freed in Z3 once they
are created.  Caching tactics per thread will reduce the amount of memory
leaked.
> BackendZ3: Store a copy of tactics in TLS.

- claripy/ast/bool.py
- claripy/operations.py
- tests/test_expression.py
Adds a reverse operation for for ite_cases and tweaks the And simplifier so it produces sane results. The one concern is, as always, whether the simplifier tweaks are too heavy. I don't think they should be, but I'd like another pair of eyes on it.
> Reverse ite cases

- claripy/ast/base.py
- claripy/backends/__init__.py
- claripy/operations.py
- Replace references to 'I' with either BVV or nothing, depending on context
- Replace references to the list of leaf operations with `operations.leaf_operations`
- Add VSA ops to list of leaf operations
- Remove some dead code from the base constructor
partner to angr/angr#1155
> Spring cleaning july 2018

- claripy/vsa/bool_result.py
so, um, a horrifying amount of claripy seems to want to be able to put strided interval objects in sets. Sets require members to be hashable and comparable. Comparison between two strided intervals currently does not return a bool. How did this ever work???????????????????????????????
Closes #94
> Add __bool__ to VSA bool results

- claripy/backends/backend_vsa.py
- claripy/frontend_mixins/model_cache_mixin.py
- claripy/frontends/full_frontend.py
- claripy/vsa/valueset.py
Without the `__mod__` operation implemented for `ValueSet` it is impossible to make a `full_init_state` with mode set to 'static':
```python
In [11]: p = angr.Project('/bin/grep')                                                                                         
WARNING | 2018-10-25 12:56:18,144 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
In [12]: p.factory.full_init_state(addr=p.entry, mode='static')                                                            
---------------------------------------------------------------------------
BackendUnsupportedError                   Traceback (most recent call last)
~/embedi/angr-dev/claripy/claripy/backends/__init__.py in convert(self, expr)
159 …
```
> ValueSet: implement __mod__ operation

- claripy/frontend_mixins/model_cache_mixin.py
- tests/test_solver.py
This should heavily reduce memory usage and maybe runtime for rex's reconstraining step.
> create gratuitous model when we add a first, trivial constraint

- claripy/backends/backend_z3.py
Solves the issue of "memory fragmentation" when too many Z3 solvers are created. Should be enabled by default for symbolic tracing or whenever memory pressure occurs.
> Allow reusing per-thread Z3 solvers. Controlled by envvar REUSE_Z3_SOLVER.

- claripy/balancer.py
[Concat](https://github.com/angr/claripy/blob/7dac4326d7aa2658119adbdb6225756c600bc984/claripy/bv.py#L295) expects its arguments passed as *args, not as a tuple.
> Balancer: unpack arguments for Concat

- claripy/ast/base.py
- tests/test_expression.py
`__nonzero__` is no longer used for `assert, if, and bool()`. `__bool__` is the new king.
This should not be merged until we merge https://github.com/angr/claripy/pull/106, to avoid conflict risk.
> fix assertion on bool conversion on ASTs

- claripy/backends/backend_z3.py
Thanks to the recent patch that makes claripy less recursive, we are
probably releasing Z3 objects more often than before. A negative
consequence is that our Z3 AST hash, which uses to heavily rely on memory
addresses of Z3 ASTs, now have a much higher chance to collide. This patch
solves this problem in a painful way: Always check if the cached Z3 object
is the same as the one being abstracted, and do not return the cached one
if they are not equal to avoid AST collisions. It will surely impact the
speed, but it is still better than returning incorrect results.
Thanks @basher for reporting another issue that led us to find this bug.
Update: The old fix introduces way too many equality checks, which greatly slows down simplifications when ASTs are big and deep. Here is a better solution: …
> BackendZ3: Resolve Z3 AST hash collisions.

- claripy/simplifications.py
- tests/test_simplify.py
Simplifies `Reverse(Extract(hi, lo, Reverse(x)))` to `Extract(bits-lo-1, bits-hi-1, x)` when possible.
> Simplification: Add a Rev-Extract-Rev simplifier.

- claripy/backends/backend_z3.py
I'm actually not sure whether it is supposed to be a `int` type. 
If it is, I will open up an issue because I encountered a case where `bv_len` is a `int`
> int type does not have size method

- claripy/ast/base.py
The first fixes the case where kwargs['annotations'] is None.
The second fixes the case with a default argument value, since 'None is False' is Falsey.
> Fixed two bugs with annotation arguments

- claripy/frontend.py
As I could not find any more lost docstrings, I've written these ones based on experimentation and code reading. I hope that I've got them right.
More fixes to issue #19
> Add docstrings to claripy.Frontend

- claripy/ast/base.py
- claripy/simplifications.py
- tests/test_simplify.py
requires running simplifications during ite excavation to get tests to pass, but honestly that's not too bad of a deal tbh
> Let flattening simplifiers evaluate multiple concrete args together

- claripy/backends/backend_z3.py
Otherwise, we will try to abstract z3's normalized version of the constraints. This is undesirable for my usecase.
> Cache abstraction info for constraints when tracking is enabled

- claripy/ast/strings.py
- claripy/backends/backend_concrete.py
- claripy/backends/backend_z3.py
- claripy/frontend_mixins/model_cache_mixin.py
- claripy/strings.py
This patch implements all the claripy string operations (except IsDigit) in the z3 backend. It also adds a new string operation, UnitStr, which creates a single-char string from a bitvector. I am using this code for experiments with making the simprocedures for `<string.h>` functions faster by passing constraints to z3's powerful string solver, `z3str3`. Any feedback on the changes would be welcome. This is my first PR to claripy, so apologies in advance for any errors or misunderstandings :)
Edit: I have tested `StrIndexOf` with `StringS` and `StringV` values on my machine and it works fine (that's the main operation I need for my work in angr). The other operations have not been tested, but should work based on how similar their implementations are to `StrIndexOf`. If anyone is actually …
> Implement operations from ast/strings.py in the z3 backend

- claripy/frontends/composite_frontend.py
- tests/test_solver.py
Until now, the composite solver would loop through all of its children to check if it is satisfiable. Even if each check hit the child's cache, looping through the children would make this process slow. Now, the composite solver will only check solvers that it does not already know to be satisfiable.
One specific side-effect of this is that if someone accesses the children directly, and adds constraints to them, the composite solver won't know to re-check. There were already other parts of the composite solver that would break in that scenario, though, so I think that's okay.
> Make composite solver more efficient in the presence of many independent constraint sets

- claripy/frontends/composite_frontend.py
In the CompositeFrontend.unsat_core function, extra_constraints was not passed to child solvers. Therefore it cannot get an unsat core if it's the extra_constraints causing the unsatisfiability.
> fix missing extra_constraints in CompositeFrontend.unsat_core()

- claripy/backends/backend_concrete.py
Somehow in the linked issue, BackendConcrete was getting hung up on stuff like Xor(True, Xor(True, True)). This resolves that.
> Implement more boolean operations in BackendConcrete

- claripy/frontends/composite_frontend.py
For some reason, the old code would split a solver twice while reabsorbing it. This can be a costly procedure, so let's do it once.
> measure twice, split once

- claripy/ast/bool.py
Currently, `ite_dict` turns a dictionary lookup into a claripy expression by using a linear series of if-then-else statements. This creates expression trees whose depths are equal to the size of the dict. For a dict with, say, 200 elements, this creates a RecursionError in claripy. This came up recently for me when [hooking an instruction that was most easily implemented by a table](https://ohaithe.re/post/624142953693249536/uiuctf-2020-cricket32) of 256 elements, and claripy crashed.
This PR replaces `ite_dict` to use a binary search tree when the dict gets biggish. It would be risky to do this for `ite_cases`, since there they might be an assumption that it tries the cases in the given order, in the event that two cases are both true. But for a dict, only one case can be true, so this …
> Change ite_dict to use binary search tree

- claripy/balancer.py
- Balancer may incorrectly report False truisms as sat.
- Balancer may incorrectly remove Extract() when signed comparisons are
used.
> Fix two issues that are causing VSA tests to fail.

- claripy/operations.py
This removes the 'Reversed' operation and the set it was defined in from operations.py, as nothing referenced either in all of claripy.
> Removed dead code from operations.py

- claripy/simplifications.py
- tests/test_simplify.py
Otherwise it makes static analysis (especially decompiler) confused when it generates code like `Extract(10, 0, some_expr)`, since extracting 11 bits and creating a new 11-bit expression cannot be easily modeled in C code.
> Ideally, simplifiers should not change sizes of sub expressions.

- claripy/ast/fp.py
- claripy/vsa/strided_interval.py
We no longer need to support python2.
> Remove long from claripy; it was unified with int before python 3

- claripy/ast/bv.py
- claripy/operations.py
The divmod op doesn't seem to have any backend support and seems unused. It also seems like shoving a python op into the AST rather than making a python wrapper (for example it would be like making `__radd__` a legitimate op rather than a python wrapper for the add `__add__` op. This was related to my conversation with @ltfish and @zardus
> __divmod__ op removed

- claripy/ast/bv.py
- claripy/ast/fp.py
- claripy/bv.py
- claripy/fp.py
- claripy/operations.py
- claripy/vsa/discrete_strided_interval_set.py
- claripy/vsa/strided_interval.py
- tests/test_bv.py
`__div__` is python2. We now have `__floordiv__` and `__truediv__`. Claripy already had `__div__` simply aliasing one of the two in all use cases; these have been removed since we no longer support python2.
Related angr PR: merged
> Remove all `__div__` uses from claripy

- claripy/ast/strings.py
- claripy/backends/backend_smtlib.py
- claripy/backends/backend_z3.py
- claripy/operations.py
- claripy/simplifications.py
- claripy/strings.py
- tests/test_backend_smt.py
StrExtract is not used much as far as I can tell; is buggy / incorrect, and depends on z3 code that is buggy / has incorrect documentation. Furthermore, it is just an alias of SubStr
I replaced usages of StrExtract with their equivalent SubStr calls; so this should not affect runs much; however, since StrExtract was buggy, the call to SubStr (since I converted the arguments) likely is too.
> rm StrExtract

- claripy/ast/strings.py
- claripy/backends/backend_z3.py
UnitStr was unused as far as I know and also did not do was intended; it returned a sequence not a string so it probably wasn't use-able in the first place in ASTs.
> Rm unit str

- claripy/backends/backend_z3.py
Before we used the wrong enum and were lucky the two numbers happened to match. Switch from `Z3_param_kind` enum to` Z3_parameter_kind` enum
> Fix wrong enum type to prevent future bugs.

- claripy/ast/base.py
Some Python distributions do not include the _md5 module.
> Fallback to hashlib if _md5 is unavailable

- claripy/ast/fp.py
- tests/test_fp.py
By default, Python treats floating point numbers as double-precision floats. This becomes a problem when creating concrete single-precision floating point values since value stored would still be double-precision. To work around this, we pack the number to bytes, unpack those bytes and create an FPV from the resulting floating point value.
> Correctly create single-precision floating-point values

- claripy/simplifications.py
Having nodes with a single argument, e.g. "add(42)" is rather annoying as they look the same but don't behave the same (e.g. for `structurally_match`) as their lone arg.
> Avoid single-argument nodes in simplifications

- claripy/simplifications.py
`(a == b).is_true()` will create a claripy AST, which will involve applying annotations if a or b are annotated. This is completely unnecessary if we can easily tell a and b are not equal by testing their operations or arguments. This PR fixes a few places to avoid creating redundant intermediate ASTs.
> Simplifications: Create fewer redundant ASTs.

- claripy/ast/__init__.py
- claripy/py.typed
- setup.py
The delayed import construct completely confuses mypy, so this hides it
from the type checker. To allow mypy to recognize that claripy has basic
typing support the `py.typed` file is also added to the `setup.py`
> Allow usages of BV to be typechecked

- claripy/simplifications.py
Adds handling to `zeroext_comparing_against_simplifier` when `Concat` is used like a `ZeroExt`.
Helps to reduce:
```
[<Bool (0 .. (if reg_rdi_19_64{UNINITIALIZED} == 0x0 then 1 else 0)) != 0>]
[<Bool (0 .. (if reg_rdi_19_64{UNINITIALIZED} == 0x0 then 1 else 0)) == 0>]
```
to:
```
[<Bool reg_rdi_19_64{UNINITIALIZED} == 0x0>]
[<Bool reg_rdi_19_64{UNINITIALIZED} != 0x0>]
```
This `ZeroExt+Concat` handling pattern is used in other simplifiers; maybe we should just add a simplifier to convert `Concat(BVV(0,n) .. x) => ZeroExt(n, x)` to simplify some of these handlers, but it's left for future work.
> Also handle Concat in zeroext_comparing_against_simplifier

- claripy/bv.py
> Use a binary shift instead of exponentiation in `claripy.Extract`

- claripy/bv.py
`claripy.Extract` currently uses a mask of `f` 1-bits, and the resulting value is put in a `BVV` with only `f - t + 1` bits. The result is the same if only `f - t + 1` bits were used in the initial mask, so this PR makes the mask just as big as it should be to avoid another truncation when the `BVV` is constructed. This improves the performance if both `f` and `t` are large.
> Make the mask `claripy.Extract` uses smaller to avoid double truncate

- claripy/backends/backend_z3.py
- claripy/frontends/full_frontend.py
This results in increased incrementalism and thus speeds up further queries (See https://github.com/Z3Prover/z3/issues/556). Leads to 10-25% reduction in execution time in my private benchmarks.
> Z3: clone the solver instead of adding constraints to a fresh instance

- setup.cfg
As angr requires a minimal Python version 3.8 and there is no use of __future__ and builtins, I think it's safe to remove future from dependencies.
> remove dependency future

- claripy/ast/base.py
- tests/test_annotations.py
This PR makes several improvements:
- Add a fast path in `make_like()` for adding or changing annotations of an existing AST.
- Avoid repeated lookups of `itertools.chain` and `itertools.chain.from_iterable`.
- Allow removing annotations when `annotate()` is called, which avoids creating intermediate annotated ASTs when replacing existing annotations on an AST.
> Annotate ASTs faster.

- setup.cfg
I think this is the cause of CI suddenly falling over as noticed in https://github.com/angr/cle/pull/341
> pin to z3 == 4.10.2.0 since 4.11 seems to have introduced serious performance regressions

- claripy/bv.py
- tests/test_expression.py
related to #271 
when shifting a BV by a negative amount (as might happen when symbolically executing it), it throws a `ValueError: negative shift count` because the count is taken as signed. that should not be the case and this PR fixes that.
also added a bunch of test for the various shift behavior.
btw, I didn't keep the `o.signed < self.bits` branch, as the value is already sanitized in `__init__`, but maybe I missed smth?
> expr: fix shift with negative operand

- claripy/ast/base.py
- claripy/ast/bits.py
- claripy/ast/strings.py
- claripy/operations.py
Fix for: https://github.com/angr/claripy/issues/292
Warning: This changes the semantic meaning of `String.length` from byte length to bit length; use `.string_length` for byte length.
Also, `.size()` and `__len__` are both defined by `Bits`, they also change from byte to bit length; we can override these functions in the `String` class if we desire before merging this.
> Change Bits and String not to edit `ast.length`

- claripy/backends/backend_z3.py
The old function did not exist in Z3
> Fix: Update z3 usage to use actual z3 functions

- claripy/backends/backend_z3.py
This PR removes dead code. I consulted with @ltfish on this and the response was to PR it and see if anything breaks
> `backend_z3.py` did not use the simplification cache

- claripy/backends/backend_z3.py
This is a draft since I want to see if the 'unneeded imports' were actually needed because of some eval-y behavior hidden in `backend_z3.py` via the CI.
> lint `backend_z3.py`

- claripy/backends/backend_z3.py
Fixes: https://github.com/angr/claripy/issues/315
> Pass Z3 StringVs with implicit zero pads explicitly

- claripy/backends/backend_z3.py
- tests/test_z3.py
This PR:
1. Condenses min/max into a single function body to avoid code duplication
2. Fixes the bug where `_max` uses `GT` instead of `GE` like min does.
3. Only keeps the latest binary search constraint during the search rather than every previously valid constraint; this should greatly decrease the number of constraints passed to Z3.
> Condense min/max into singular function

- setup.cfg
This bumps pysmt to be a stable version. Some tools like pipenv are weird when pinning dev versions.
> Bump pysmt to stable version

- claripy/frontends/composite_frontend.py
Under arcane circumstances I don't understand, this can happen. It didn't happen in a venv from a few days ago, but it happens now, despite using the same pinned commits of the angr repos. It also only happens with pypy and not CPython.
> Handle rare edge case where solver has 0 variables

- claripy/frontends/full_frontend.py
in some cases, such as no constraints in the state, this code was calling z3 twice for a single eval. @zardus you might want to check this is the correct way to fix it
> Fix double z3 check

- claripy/ast/base.py
- claripy/ast/strings.py
- claripy/backends/backend_concrete.py
- claripy/backends/backend_vsa.py
- claripy/backends/backend_z3.py
- claripy/balancer.py
- claripy/frontend_mixins/constraint_fixer_mixin.py
- claripy/frontend_mixins/model_cache_mixin.py
- claripy/frontends/composite_frontend.py
- claripy/frontends/full_frontend.py
- claripy/simplifications.py
- claripy/utils/deprecated.py
- claripy/vsa/bool_result.py
- claripy/vsa/discrete_strided_interval_set.py
- claripy/vsa/strided_interval.py
- pyproject.toml
On master we are still using `setup.cfg` to set build properties. This meant ruff couldn't autodetect the minimum python version, defaulting to whatever its minimum version is, probably 3.8. This explicitly sets it for ruff and applies fixes for it.
> Set ruff target version to Python 3.10

- claripy/ast/base.py
I think there was a mistake in this commit: https://github.com/angr/claripy/commit/b6928e2164a5964f465961715880b9cf773bf9ea
Because of this mistake, eager_backends has always been set to None.
> Don't always nop out eager backends

- claripy/ast/base.py
I have a function where this makes the difference between the RDA finishing in ~3 seconds in comparison to it not finishing after 8 hours.
The `uneliminatable_annotations` are already deduplicated in the same way
> De-duplicate relocatable_annotations when creating AST

- claripy/ast/base.py
- tests/test_annotations.py
In #411 I changed the behavior of _apply_to_annotations. This broke the "clear annotations" use case that was used in angr. Rather than having an implicit use to handle this, let's add an api specifically for this. Any use of _apply_to_annotations outside of Base.py should be avoided.
> Add clear_annotations to Base

- claripy/ast/strings.py
Bit length vs Byte length bug fix in string_length
> Bit length vs Byte length bug fix in string_length

- claripy/ast/__init__.py
- claripy/ast/int.py
- claripy/ast/vs.py
These appear to be used nowhere and have no history other than being leftovers after refactors and formatting changes.
link: https://github.com/angr/angr/pull/4717
> Remove unused Int and VS AST objects

- claripy/ast/bool.py
- claripy/ast/bv.py
- claripy/ast/fp.py
- claripy/ast/strings.py
- claripy/operations.py
Doesn't appear to ever have been used, even in the commit it was added in. The parameter is set many times, but never used.
> Remove unused bound arg from op

- claripy/frontend.py
- claripy/frontend_mixins/composited_cache_mixin.py
- claripy/frontend_mixins/concrete_handler_mixin.py
- claripy/frontend_mixins/constraint_deduplicator_mixin.py
- claripy/frontend_mixins/constraint_expansion_mixin.py
- claripy/frontend_mixins/constraint_filter_mixin.py
- claripy/frontend_mixins/constraint_fixer_mixin.py
- claripy/frontend_mixins/eager_resolution_mixin.py
- claripy/frontend_mixins/model_cache_mixin.py
- claripy/frontend_mixins/sat_cache_mixin.py
- claripy/frontend_mixins/simplify_helper_mixin.py
- claripy/frontend_mixins/simplify_skipper_mixin.py
- claripy/frontend_mixins/solve_block_mixin.py
- claripy/frontends/composite_frontend.py
- claripy/frontends/constrained_frontend.py
- claripy/frontends/full_frontend.py
- claripy/frontends/hybrid_frontend.py
- claripy/frontends/replacement_frontend.py
This removes all the *args and **kwargs from the frontends and frontend mixins. This is actually a regression typing wise because I was trying to get mypy to be happy about all of the definitions, and having some methods have type constraints while others didn't prevented that. I will follow up with a PR re-introducing types more uniformly.
> Dekwargsify frontend

- claripy/ast/base.py
It is only used in one place and seems unnecessary.
> Inline __init_with_attributes__

- claripy/ast/base.py
Seems unused and adds complication to the imports.
> Remove unused Base._identity_vars method

- claripy/frontends/composite_frontend.py
- tests/test_merging.py
Simple example to reproduce:
```python
s1 = claripy.SolverComposite()
s2 = claripy.SolverComposite()
m = claripy.BVS("m", 8)
w = claripy.BVS("w", 8)
s1.add(w == 0)
_, sm = s1.merge([s2], [m == 0, m == 1])
sm.eval(w, 2) # returns (0,), despite w being unconstrained in s2
```
This can also be reproduced though some fairly trivial merges in angr:
```python
s1 = angr.SimState(arch='ARM', mode='symbolic')
x = s1.solver.BVS('x', 32)
s1.regs.r0 = x
s1.add_constraints(s1.regs.r0 == 42)
s2 = s1.copy()
y = s2.solver.BVS('y', 32)
s2.regs.r0 = y
s2.add_constraints(s2.regs.r0 == 43)
m, _, merged = s1.merge(s2)
print(m.solver.eval_upto(m.regs.r0, 10)) # prints [42], but it should be [42, 43]
```
I will admit I have not been working with claripy all that long, so let me know if there's something …
> Fix incorrect merge in composite solver when child solvers are empty

- claripy/__init__.py
- claripy/ast/base.py
- claripy/ast/bool.py
- claripy/ast/bv.py
- claripy/ast/strings.py
- claripy/backend_manager.py
- claripy/frontend_mixins/eager_resolution_mixin.py
- claripy/frontends/replacement_frontend.py
- tests/test_expression.py
These are never actually utilized and we want to remove the backend manager anyways. Also removes a handful of pointless loops which are usually just calling the concrete backend.
> Remove eager_backends and quick_backends

- claripy/frontend_mixins/model_cache_mixin.py
These two functions got rewritten by ruff in a very unappealing way, this rewrites them to be more close to the original while still satisfying the beast. Someday maybe we'll be able to use match statements.
> Fix weirdly formatted functions in ModelCache

- claripy/ast/base.py
BackendConcrete will return either a (non-AST) BVV, or a bool. To unpack the BVV into a Python int, it calls `.value`. This fails in the case that it returns a bool, which can be returned directly.
> Fix AttributeError when calling concrete_value on a Bool

- claripy/backends/backend_concrete.py
Seems arbitrary? I wonder what breaks
> Allow BackendConcrete to handle empty BVV and StringV

- claripy/ast/base.py
This will make it easier to query annotations on an object, especially the presence of a RegionAnnotation.
> Add has_annotation_type() method to Base

- claripy/bv.py
- tests/test_bv.py
`claripy.ESI` makes an `ast.BV` with a value of `None`, the concrete backend trips on this during the union op. This makes it handle it a bit.
> Better handle None values in BV

- claripy/ast/base.py
I might be wrong but I think this might be like 100+ bytes per object, given there is exactly one member? That could actually add up to something.
> Add __slots__ to ASTCacheKey

- claripy/ast/bool.py
- claripy/frontend_mixins/constraint_filter_mixin.py
- claripy/frontend_mixins/model_cache_mixin.py
- claripy/frontend_mixins/sat_cache_mixin.py
- claripy/frontends/replacement_frontend.py
- claripy/simplifications.py
- tests/test_simplify.py
- tests/test_solver.py
The rationale for this change is that this should make it easier to simplify the import machinery in claripy, because the true and false objects won't be created until after all of claripy is imported. Right now when making changes, we run into issues importing because things expect all the backends and such to exist when an AST is being created or handled.
https://github.com/angr/angr/pull/4871
https://github.com/angr/angr-platforms/pull/74
> Make true and false functions

- claripy/ast/strings.py
- claripy/backends/backend_z3.py
- claripy/operations.py
- claripy/strings.py
- tests/test_strings.py
This removes the `bitlength` field from certain string ops, which controlled the length of the BV returned when a integer value would be returned by the equivalent op in Z3. The best fix for this would be to actually support an Integer type in claripy, but for now this change is simple and if you need more than a 64 bits to express the length or index of a string, you have probably run into far more severe issues at this point anyways.
https://github.com/angr/angr/pull/4875
> Always use BV64 returns in string ops

- claripy/ast/base.py
- claripy/backends/backend.py
- claripy/backends/backend_concrete/backend_concrete.py
- claripy/backends/backend_vsa/backend_vsa.py
- claripy/backends/backend_z3.py
Like other backend methods, there exists a "regular" and underscore-prefixed version of the same method. In the case of simplify, nothing actually uses this. The concrete and vsa backends use the default "just return it" implementation, and z3 overrode the parent simplify and errored on _simplify. So let's just remove the _simplify method to keep this tidier.
> Simplify simplify routines

- claripy/ast/base.py
Seems like this should be trivial, and faster than the fastpath
> Change Base.concrete implementation to return `not self.symbolic`

- claripy/__init__.py
- claripy/algorithm/__init__.py
- claripy/algorithm/simplify.py
- claripy/ast/base.py
- claripy/frontend/constrained_frontend.py
The basic plan here is to remove the last backend references in the AST by just moving many of the functions to a new algorithms subpackage. This improve modularization by separating the AST from the various operations that can be preformed on an AST.
> Move simplify from base.py to new algorithm sub-package

- claripy/ast/base.py
- claripy/operations.py
- claripy/simplifications.py
This is a bunch of nonsense to handle the case where you have an Extract over a Concat where the bounds of the Extract select one of the args of the Concat, but the other arg of the Concat has a relocatable annotation that gets grafted onto the arg being extracted.
> Allow simplifications to handle annotations

- tests/test_simplify.py
- tests/test_vsa.py
> Remove spurious uninitialized kwargs from tests

- claripy/backends/backend_concrete/fp.py
- tests/test_fp.py
Fixes https://github.com/angr/claripy/issues/571, adds two test cases
> Fix passing backend FPV objects to math.isnan and math.isinf

- claripy/backends/backend_z3.py
- tests/test_z3.py
CPython 3.11 introduced integer string conversion length limit (see https://docs.python.org/3/library/stdtypes.html#integer-string-conversion-length-limitation). We determined that this security protection does not apply to the threat model that angr would face, and in fact, causes issues when we deal with really long strings and integers. Therefore, we bypass the integer conversion limit in this PR.
We also monkey-patch the Z3 Python binding so that it can accept long integers in constraints.
> BackendZ3: Bypass integer string conversion limit.

- claripy/backends/backend_vsa/balancer.py
fix error TypeError: Base.__new__() got an unexpected keyword argument 'min'
> Claripy BVS() argument fix

- claripy/ast/bv.py
- claripy/backends/backend_z3.py
- claripy/operations.py
- tests/test_ast.py
This is a test to see if this is actually used anywhere. It isn't supported in any backends, and smtlib nor z3 supports this op.
> Remove pow op from BVs

- claripy/ast/bv.py
No backends supported this, would be surprised if anything depended on it.
> Remove BV __abs__ op

- claripy/backends/backend_z3.py
Rather than directly raising KeyboardInterrupt, use signal.default_int_handler as it is Callable.
> simplify signal handler as signal.default_int_handler is callable

- claripy/ast/fp.py
- tests/test_regressions.py
Fixes fpToFPUnsigned from having a None length when being returned from the z3 backend. Fixes https://github.com/angr/angr/issues/5456
> Add fpToFPUnsigned bound op

- claripy/backends/backend_z3.py
- tests/test_z3.py
> Correctly handle RotateLeft/Right sizes in Z3 backend
