angr/claripy

setup.py
Adding url and description to setup.py
=> Adding url and description to setup.py

claripy/__init__.py, claripy/ast/base.py, claripy/ast/bool.py, claripy/ast/bv.py, claripy/ast/fp.py, claripy/backend.py, claripy/backend_object.py, claripy/backends/backend_z3.py, claripy/balancer.py, claripy/frontends/caching_frontend.py, claripy/frontends/composite_frontend.py, claripy/frontends/constrained_frontend.py, claripy/frontends/hybrid_frontend.py, claripy/frontends/replacement_frontend.py, claripy/vsa/discrete_strided_interval_set.py, claripy/vsa/strided_interval.py, claripy/vsa/valueset.py
More docstrings formatting, I also reformatted 2 files that were using tabs instead of spaces.
=> Reformatting of docstrings.

claripy/ast/bv.py
=> Add check for unicode string value in BVV

claripy/operations.py, claripy/utils/__init__.py, claripy/utils/orderedset.py
This allows us to simplify expressions like (a ^ a ^ b) to b.
=> Implement an argument filter for flattening simplifier.

claripy/ast/base.py, claripy/frontends/replacement_frontend.py
Nothing major. It's just a better coding style.
=> Use try... except KeyError to test if the replacement cache contains a key.

claripy/__init__.py, claripy/ast/base.py, claripy/ast/bool.py, claripy/ast/bv.py, claripy/backends/backend_concrete.py, claripy/backends/backend_vsa.py, claripy/backends/backend_z3.py, claripy/backends/backend_z3_parallel.py, claripy/backends/backendremote.py, claripy/backends/remotetasks.py, claripy/balancer.py, claripy/bv.py, claripy/frontend.py, claripy/frontend_mixins/constraint_fixer_mixin.py, claripy/frontend_mixins/debug_mixin.py, claripy/frontends/composite_frontend.py, claripy/frontends/replacement_frontend.py, claripy/operations.py, claripy/ops.py, claripy/vsa/discrete_strided_interval_set.py, claripy/vsa/strided_interval.py, claripy/vsa/valueset.py, tests/regressions.py, tests/test_balancer.py, tests/test_expression.py, tests/test_solver.py, tests/test_strided_intervals.py, tests/test_vsa.py
It's a long way from being compatible with python3, but it should help.
Clean up print statements, and references to long.
Reorder imports, too.
It contains multiple commits, because I have no idea how to use git properly. But the diff is the right one.
=> Make the code more python3-compatible

claripy/bv.py, tests/test_bv.py
This commit fixes angr GitHub issue #773
(https://github.com/angr/angr/issues/773).
=> BV: Catch ZeroDivisionErrors for more operations.

claripy/frontend_mixins/model_cache_mixin.py
@zardus as discussed on slack, please merge this and leave #60 here for a while
=> Fix model cache

claripy/backends/backend_z3.py
=> Pop solver during min with extra constraints, makes it match max

claripy/operations.py
Thanks Ben Rodes from Kudu Dynamics for reporting this bug.
=> boolean_and_simplifier: Check if there is only one argument again after simplification.

claripy/backends/backend_z3.py
Remember folks, the contents of tls must be initialized in each thread!
Fixed extra_bvs_data to use the same pattern as the rest of claripy for dealing with this 
Note that libz3 may still segfault when multithreading; we know about it, but have not managed to track it down through aggressive audits.  
Does not happen in all circumstances, i have one symexec-based analysis ripping apart a 48-thread machine right now without issues.
=> Fix thread safety by moving extra_bvs_data to a property

README.md, claripy/ast/base.py, claripy/ast/bool.py, claripy/ast/bv.py, claripy/ast/fp.py, claripy/backends/backend_z3.py, claripy/frontend.py, tests/test_expression.py, tests/test_vsa.py
=> Migrate to Python 3

claripy/vsa/discrete_strided_interval_set.py, tests/test_vsa.py
Closes https://github.com/angr/claripy/issues/95
=> DiscreteStridedIntervalSet: add reverse() method (closes #95)

claripy/ast/base.py
Closes https://github.com/angr/claripy/issues/111.
I've also tried to change `_burrow_ite()` to be non-recursive, but failed to do so in a reasonable amount of time. Let me know if `_burrow_ite()` is also causing any troubles, and I'll revisit it later.
=> Base: make _excavate_ite() non-recursive

claripy/__init__.py, claripy/ast/base.py, claripy/backends/backend_concrete.py, claripy/simplifications.py, tests/test_simplify.py
- Avoid re-scanning large args arrays again and again during AST
creation.
- Make Bool.is_false() and Bool.is_true() faster.
- Use set instead of OrderedSet in several places for better
performance.
=> General speed improvement in AST creation and simplification.

claripy/simplifications.py, tests/test_simplify.py
- Rotate-shift-mask simplifier.
- LShR simplifier.
- Add more cases to `__rshift__` simplifier.
=> Add several simplifiers.

claripy/balancer.py, tests/test_balancer.py
Convert N op var to var op N before future balancing.
=> Balancer: Properly handle N op var.

claripy/ast/strings.py, claripy/backends/backend_smtlib_solvers/abc_popen.py, claripy/backends/backend_smtlib_solvers/z3_popen.py, claripy/backends/backend_smtlib_solvers/z3str_popen.py
Resolved issue #128 and fixed a missing import in solver popen classes
=> Removed replace method in ast.string class 

claripy/ast/base.py, claripy/simplifications.py
Now make_like() will try to simplify the given expression one more time.
By default it does not attempt to simplify expressions unless explicitly
specifying "simplify=True". This is to keep the compatibility with many
existing simplifiers that don't support multi-arg versions of certain
operations (e.g., Add and Or).
I'm also trying to smuggle in a new simplifier:
Simplifying `ZeroExt(A, ZeroExt(B, x))` to `ZeroExt(A + B, x)`.
=> make_like: Support simplifying expressions.

claripy/simplifications.py, tests/test_simplify.py
reversed() returns an iterator! Isn't py3 great? :)
=> Do not pass iterators into make_like or you're gonna have a bad time(tm)

claripy/backends/backend_z3.py
=> Preserve annotations better through z3 operations

claripy/frontend.py
=> Restore lost docstrings on claripy.Frontend

claripy/ast/base.py, claripy/operations.py, tests/test_ast.py
Fix issue #141 .
I've converted the iterated AST processing algorithm to a recursive one, and I've modified `shallow_repr` to consider infix operation precedence level.
=> Fix issue #141 

claripy/ast/fp.py, claripy/backend_object.py, claripy/backends/backend_concrete.py, claripy/backends/backend_z3.py, claripy/fp.py, claripy/operations.py, claripy/simplifications.py, setup.py, tests/test_solver.py
Signed-off-by: Sebastiano Mariani <mariani.sebastiano@gmail.com>
=> Updated backend Z3 to work with the newest Z3 version

claripy/frontend_mixins/model_cache_mixin.py, tests/test_solver.py
Also a bonus test case to demonstrate the issue :-)
=> This fixes an issue where, due to overzealous caching, `min` and `max` could return incorrect results

claripy/frontend_mixins/model_cache_mixin.py
Thank @badnack for a 10-hour collaborative debugging session over Slack.
=> Filter models returned by Z3 and discard unexpected variables.

claripy/simplifications.py, tests/test_simplify.py
Sync: https://github.com/angr/angr/pull/2419
=> Add a few more __eq__ and __ne__ simplifiers.

claripy/ast/bv.py, claripy/fp.py, claripy/vsa/discrete_strided_interval_set.py
Fixes the lint errors preventing 205 from being merged.
=> Fix lint errors

claripy/backends/__init__.py, claripy/backends/backend_concrete.py, claripy/backends/backend_vsa.py, claripy/backends/backend_z3.py, claripy/frontend.py, claripy/frontend_mixins/constraint_expansion_mixin.py, claripy/frontend_mixins/model_cache_mixin.py, claripy/frontends/composite_frontend.py, claripy/frontends/constrained_frontend.py, claripy/frontends/full_frontend.py, claripy/frontends/hybrid_frontend.py, claripy/frontends/light_frontend.py, claripy/frontends/replacement_frontend.py, tests/test_solver.py
=> Implement signed min and max

claripy/backends/backend_z3.py
This would return true before if an unexpected exception occurred; this PR fixes that.
=> fix backend_z3 _satisfiable bug

claripy/ast/base.py
It is to solve this: https://github.com/angr/angr/issues/2867#issuecomment-901521771. You can check the issue for more details.
=> propagate anno

claripy/simplifications.py
=> Fix And(a, a)

claripy/backends/backend_smtlib_solvers/__init__.py
Fixes: https://github.com/angr/claripy/issues/294
=> Get rid of six dependency

claripy/backends/backend_z3.py
'Concat args should all be ASTs, this check / loop is unnecessary
=> Remove wasted instructions

tests/test_solver.py
Fixes: https://github.com/angr/claripy/issues/303
=> Edit test_solver so tests actually run

claripy/ast/bv.py, claripy/operations.py
Implements: https://github.com/angr/claripy/issues/305
=> Replace __pos__ with lambda x: x

claripy/frontends/composite_frontend.py, tests/test_solver.py
Close https://github.com/angr/angr/issues/3604.
=> CompositeSolver: The merged child solver should be of the transitive closure of variables.

claripy/backends/backend_z3.py
Not supported because z3 does not supported strings
https://github.com/Z3Prover/z3/discussions/6443
=> String symbols abstraction explicitly not supported by z3 backend

claripy/backends/backend_z3.py
Fixes: https://github.com/angr/claripy/issues/298
=> Fix Z3 StringV abstraction

claripy/vsa/strided_interval.py
Remove `import ipdb; ipdb.set_trace()` statements where better alternatives exist.
=> Remove debugging statements

claripy/simplifications.py
This should fix this issue https://github.com/angr/claripy/issues/338
=> Fix AttributeError in boolean_and_simplifier when _flatten_simplifier returns None

claripy/backends/backend_z3.py
Fixes an issue reported privately.
=> Add backendz3 bits for fpToFPUnsigned

setup.cfg
Gonna try this again and see where we stand
=> Upgrade z3 to 4.13.0.0

claripy/ast/base.py
This is something that I need to do to convert the code to rust. I figure this is a good improvement for readability and comprehension regardless.
=> Dekwargsify Base

claripy/ast/base.py, claripy/vsa/strided_interval.py, claripy/vsa/valueset.py, tests/test_balancer.py, tests/test_simplify.py, tests/test_vsa.py
angr pr: https://github.com/angr/angr/pull/4735
angr management pr: https://github.com/angr/angr-management/pull/1308
=> Remove Base.__getattr__

claripy/ast/bool.py, tests/test_expression.py
=> Add size to ast.Bool

tests/test_vsa.py
Changes made: 
- Split large test methods into smaller, focused test methods.
- Organized related tests into separate classes to enhance readability and maintainability.
- Ensured that each test method targets a specific functionality or scenario.
=> Refactored test_vsa.py to break down large test methods into smaller meaningful test methods. 

claripy/ast/bool.py, tests/test_bool.py
Fixes #392 and adds a test case
=> Fix misbalanced ite_dict

claripy/ast/base.py
This is considerably shorter, much easier to read, possibly marginally faster.
=> Simpify logic in Base.__new__

claripy/ast/base.py, tests/test_annotations.py
=> Refactor AST hashing to be more consistent

claripy/ast/base.py
https://github.com/angr/angr/pull/4802
=> Remove uc_alloc_depth field from Base

claripy/ast/base.py, tests/test_expression.py
https://github.com/angr/angrop/pull/119
https://github.com/angr/angr/pull/4803
=> Remove old compatibility methods

claripy/frontends/composite_frontend.py, claripy/solvers.py, tests/test_solver.py
sync: https://github.com/angr/angr/pull/4808
=> Remove string template from composite frontend

claripy/backends/backend_vsa.py
That commented out check preventing backend objects in args works for the test suite now!
Fixes #276
=> Prevent BackendVSA from putting BackendObjects in AST args

claripy/annotation.py, claripy/ast/bv.py, claripy/backends/backend_vsa.py, claripy/vsa/__init__.py, claripy/vsa/valueset.py
https://github.com/angr/angr/pull/4818
=> Move RegionAnnotation to annotation.py

claripy/ast/bool.py
This reverts commit b0824d422067555bac21b3873d52c637e8258485.
That PR was not supposed to be merged.
=> Revert "Allow BackendVSA to handle is_true and is_false"

claripy/ast/base.py
In profiling it seems _marginally_ faster. In theory it should also be more collision resistance.
=> Use blake2b over md5

claripy/ast/base.py
The standard library already does this for us.
=> Import pickle directly in base.py

claripy/ast/bool.py
Best-effort. Works for everything I've seen so far.
=> Add type annotations for If

claripy/ast/bv.py, claripy/ast/strings.py, claripy/backends/backend_concrete/backend_concrete.py, claripy/backends/backend_z3.py, claripy/frontend/frontend.py, claripy/operations.py, tests/test_solver.py, tests/test_strings.py
Fixes https://github.com/angr/claripy/issues/503
https://github.com/angr/angr/pull/4877
=> Remove length from String

claripy/ast/base.py, claripy/ast/bv.py, claripy/backends/backend_vsa/backend_vsa.py
https://github.com/angr/angr/pull/4885
=> Remove uninitialized, discrete_set, discrete_set_max_cardinality from BVS args

claripy/annotation.py, claripy/ast/base.py, claripy/ast/bv.py, claripy/backends/backend_vsa/backend_vsa.py, claripy/backends/backend_vsa/valueset.py, claripy/balancer.py, tests/test_expression.py, tests/test_simplify.py, tests/test_solver.py, tests/test_vsa.py
https://github.com/angr/angr/pull/4898
=> Move SI information from BVS args to annotation

claripy/ast/bv.py, tests/test_vsa.py
This gets us closer to isolating the AST
https://github.com/angr/angr/pull/4917
=> Remove SI to_conv arg

claripy/simplifications.py, tests/test_simplify.py
fix https://github.com/angr/angr/issues/4754
link: https://github.com/angr/binaries/pull/126
=> fix zeroext_comparing_against_simplifier

claripy/__init__.py, claripy/algorithm/__init__.py, claripy/algorithm/ite_relocation.py, claripy/ast/base.py, claripy/ast/bool.py, claripy/backends/backend_vsa/backend_vsa.py, claripy/balancer.py, tests/test_expression.py, tests/test_vsa.py
https://github.com/angr/angr/pull/4928
=> Move excavate_ite and burrow_ite to algorithms subpackage

claripy/ast/base.py, claripy/ast/bool.py, claripy/backends/backend.py, claripy/backends/backend_concrete/backend_concrete.py, claripy/balancer.py, claripy/frontend/mixin/model_cache_mixin.py, claripy/frontend/replacement_frontend.py, claripy/simplifications.py, tests/test_expression.py, tests/test_solver.py
https://github.com/angr/rex/pull/111
=> Remove ASTCacheKey

tests/test_vsa.py
Should fix the CI failures since yesterday
=> Downsize VSA backend when adjusting allow_dsis

claripy/__init__.py
This makes it easier for editors to find it
=> Add backends to __init__.py

claripy/algorithm/simplify.py, claripy/ast/base.py, claripy/backends/backend.py, claripy/backends/backend_z3.py
Replacing it with a cache. It wasn't really being used as intended anyways
=> Remove SimplificationLevel

claripy/__init__.py, claripy/algorithm/__init__.py, claripy/algorithm/replace.py, claripy/ast/base.py, claripy/frontend/mixin/model_cache_mixin.py, claripy/frontend/replacement_frontend.py, tests/test_expression.py
https://github.com/angr/angr/pull/4931
https://github.com/angr/rex/pull/112
=> Move replace and replace_dict to algorithms sub-package

claripy/backends/backend_vsa/balancer.py
A bunch of small improvements, but generally I just wanted to make the code a bit easier to follow.
=> Improve balancer

claripy/algorithm/simplify.py, claripy/ast/base.py, claripy/backends/__init__.py, claripy/backends/backend_any.py
This removes the `_first_backend` method from Base and allows this to be theoretically typed.
=> Add BackendAny

claripy/algorithm/simplify.py, claripy/annotation.py, claripy/ast/base.py, claripy/ast/bv.py, claripy/ast/strings.py, claripy/backends/backend_vsa/backend_vsa.py, claripy/backends/backend_z3.py, claripy/operations.py
https://github.com/angr/angr/pull/5107
=> Convert unininitalized parameter to an annotation

claripy/backends/backend_z3.py, tests/test_bv.py
=> Special case SignExt and ZeroExt to prevent None-lengths

claripy/annotation.py, claripy/ast/bv.py, claripy/backends/backend_vsa/backend_vsa.py
https://github.com/angr/angr/pull/5348
=> Remove offset field from RegionAnnotation

claripy/simplifications.py
Was triggered around level 4814.
=> bitwise_and_simplifier: do not crash on non-bit-sized ASTs

claripy/ast/bv.py, claripy/backends/backend_concrete/bv.py, claripy/backends/backend_vsa/balancer.py, claripy/backends/backend_vsa/discrete_strided_interval_set.py, claripy/backends/backend_vsa/valueset.py, claripy/backends/backend_z3.py, claripy/operations.py, claripy/simplifications.py
Fixes https://github.com/angr/claripy/issues/633
=> Standardize comparison op names
